### ISSUE TITLE
F 2.1: Load all meetings for a User

### ISSUE THREAD

**Issue by DominicSchiller** [dominicSchiller/TeaCo-Mobile#5]
Über die Restschnittstelle XYZ sollen für den in der App registrierten Nutzer alle Meetings von dem TeaCo-5 Server über den nutzerspezifischen Hash-Key geladen werden.

**Comment by ivenk** [comment]
The current implementation of a meeting is missing the suggestions. I propose to add them to the meeting class similar to users.
